In [278]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

## Data Preprocessing

In [279]:
dataset=pd.read_csv('/Users/manjilnepal/Downloads/Capstone-Final/data/Final_dataset_CS.csv',header=1)
print(dataset.shape)
dataset = dataset.drop(dataset.columns[[0,1,2]], axis=1)
dataset.head()

(445, 42)

,GGBS_kg_m3,GGBS_CaO_%,GGBS_SiO2_%,GGBS_Al2O3_%,GGBS_MgO_%,GGBS_Fe2O3_%,GGBS_SO3_%,FlyAsh_kg_m3,FA_CaO_%,FA_SiO2_%,...,Superplasticizer_%,SiO2 to Na2O (silicate modulus),Curing_Temperature,Relative Humidity,Condition,Length (mm),Breadth (mm),height (mm),CS 7 day (Mpa),CS 28 day (Mpa)
0,0.0,47.75,27.17,8.6,3.89,0.42,1.45,650.0,15.48,48.43,...,0.64,2.5,23.0,60.0,Ambient,150.0,150.0,150.0,NaN,29.00
1,650.0,47.75,27.17,8.6,3.89,0.42,1.45,0.0,15.48,48.43,...,0.64,2.5,23.0,60.0,Ambient,150.0,150.0,150.0,NaN,40.00
2,325.0,47.75,27.17,8.6,3.89,0.42,1.45,325.0,15.48,48.43,...,0.64,2.5,23.0,60.0,Ambient,150.0,150.0,150.0,NaN,45.00
3,0.0,47.75,27.17,8.6,3.89,0.42,1.45,637.0,15.48,48.43,...,0.64,2.5,23.0,60.0,Ambient,150.0,150.0,150.0,NaN,48.00
4,637.0,47.75,27.17,8.6,3.89,0.42,1.45,0.0,15.48,48.43,...,0.64,2.5,23.0,60.0,Ambient,150.0,150.0,150.0,NaN,50.32

In [280]:
dataset['Water (kg/m3)'] = pd.to_numeric(dataset['Water (kg/m3)'], errors='coerce')
dataset.dtypes

GGBS_kg_m3                          float64
GGBS_CaO_%                          float64
GGBS_SiO2_%                         float64
GGBS_Al2O3_%                        float64
GGBS_MgO_%                          float64
GGBS_Fe2O3_%                        float64
GGBS_SO3_%                          float64
FlyAsh_kg_m3                        float64
FA_CaO_%                            float64
FA_SiO2_%                           float64
FA_Al2O3_%                          float64
FA_MgO_%                            float64
FA_Fe2O3_%                          float64
FA_SO3_%                            float64
SF_kg_m3                            float64
SF_CaO_%                            float64
SF_SiO2_%                           float64
SF_Al2O3_%                          float64
SF_MgO_%                            float64
SF_Fe2O3_%                          float64
SF_SO3_%                            float64
Total NaOH (kg in 1m3 mix)          float64
Concentration (M) NaOH              float64
Total Na2SiO3 (kg in 1m3 of mix)    float64
Coarse Aggregate (kg/m3)            float64
Fine Aggregates (kg/m3)             float64
Water (kg/m3)                       float64
Activator_Binder_Ratio              float64
Water_Binder_Ratio                  float64
Superplasticizer_%                  float64
SiO2 to Na2O (silicate modulus)     float64
Curing_Temperature                  float64
Relative Humidity                   float64
Condition                               str
Length (mm)                         float64
Breadth (mm)                        float64
height (mm)                         float64
CS 7 day (Mpa)                      float64
CS 28 day (Mpa)                     float64
dtype: object

In [281]:
from sklearn.preprocessing import LabelEncoder 

le = LabelEncoder()
dataset['Condition'] = le.fit_transform(dataset['Condition'])

In [282]:
from sklearn.impute import SimpleImputer

imputer = SimpleImputer(strategy='median')
dataset = dataset.copy()
dataset[:] = imputer.fit_transform(dataset)
dataset.head()

,GGBS_kg_m3,GGBS_CaO_%,GGBS_SiO2_%,GGBS_Al2O3_%,GGBS_MgO_%,GGBS_Fe2O3_%,GGBS_SO3_%,FlyAsh_kg_m3,FA_CaO_%,FA_SiO2_%,...,Superplasticizer_%,SiO2 to Na2O (silicate modulus),Curing_Temperature,Relative Humidity,Condition,Length (mm),Breadth (mm),height (mm),CS 7 day (Mpa),CS 28 day (Mpa)
0,0.0,47.75,27.17,8.6,3.89,0.42,1.45,650.0,15.48,48.43,...,0.64,2.5,23.0,60.0,0,150.0,150.0,150.0,34.0,29.00
1,650.0,47.75,27.17,8.6,3.89,0.42,1.45,0.0,15.48,48.43,...,0.64,2.5,23.0,60.0,0,150.0,150.0,150.0,34.0,40.00
2,325.0,47.75,27.17,8.6,3.89,0.42,1.45,325.0,15.48,48.43,...,0.64,2.5,23.0,60.0,0,150.0,150.0,150.0,34.0,45.00
3,0.0,47.75,27.17,8.6,3.89,0.42,1.45,637.0,15.48,48.43,...,0.64,2.5,23.0,60.0,0,150.0,150.0,150.0,34.0,48.00
4,637.0,47.75,27.17,8.6,3.89,0.42,1.45,0.0,15.48,48.43,...,0.64,2.5,23.0,60.0,0,150.0,150.0,150.0,34.0,50.32

In [283]:
(dataset.isnull().mean())*100

GGBS_kg_m3                          0.0
GGBS_CaO_%                          0.0
GGBS_SiO2_%                         0.0
GGBS_Al2O3_%                        0.0
GGBS_MgO_%                          0.0
GGBS_Fe2O3_%                        0.0
GGBS_SO3_%                          0.0
FlyAsh_kg_m3                        0.0
FA_CaO_%                            0.0
FA_SiO2_%                           0.0
FA_Al2O3_%                          0.0
FA_MgO_%                            0.0
FA_Fe2O3_%                          0.0
FA_SO3_%                            0.0
SF_kg_m3                            0.0
SF_CaO_%                            0.0
SF_SiO2_%                           0.0
SF_Al2O3_%                          0.0
SF_MgO_%                            0.0
SF_Fe2O3_%                          0.0
SF_SO3_%                            0.0
Total NaOH (kg in 1m3 mix)          0.0
Concentration (M) NaOH              0.0
Total Na2SiO3 (kg in 1m3 of mix)    0.0
Coarse Aggregate (kg/m3)            0.0
Fine Aggregates (kg/m3)             0.0
Water (kg/m3)                       0.0
Activator_Binder_Ratio              0.0
Water_Binder_Ratio                  0.0
Superplasticizer_%                  0.0
SiO2 to Na2O (silicate modulus)     0.0
Curing_Temperature                  0.0
Relative Humidity                   0.0
Condition                           0.0
Length (mm)                         0.0
Breadth (mm)                        0.0
height (mm)                         0.0
CS 7 day (Mpa)                      0.0
CS 28 day (Mpa)                     0.0
dtype: float64

In [284]:
plt.figure(figsize=(30,20))
sns.heatmap(dataset.corr(), annot=True, cmap='coolwarm')
plt.savefig('correlation_plot.png', dpi=300)
plt.close()

## Feature Engineering

In [285]:
df = pd.read_csv('/Users/manjilnepal/Downloads/Capstone-Final/data/new_ds.csv', header=0)
df.head()

,GGBS_kg_m3,GGBS_CaO_%,GGBS_SiO2_%,GGBS_Al2O3_%,GGBS_MgO_%,GGBS_Fe2O3_%,GGBS_SO3_%,FlyAsh_kg_m3,FA_CaO_%,FA_SiO2_%,...,Superplasticizer_%,SiO2 to Na2O (silicate modulus),Curing_Temperature,Relative Humidity,Condition,Length (mm),Breadth (mm),height (mm),CS 7 day (Mpa),CS 28 day (Mpa)
0,0.0,47.75,27.17,8.6,3.89,0.42,1.45,650.0,15.48,48.43,...,0.64,2.5,23.0,60.0,0,150.0,150.0,150.0,34.0,29.00
1,650.0,47.75,27.17,8.6,3.89,0.42,1.45,0.0,15.48,48.43,...,0.64,2.5,23.0,60.0,0,150.0,150.0,150.0,34.0,40.00
2,325.0,47.75,27.17,8.6,3.89,0.42,1.45,325.0,15.48,48.43,...,0.64,2.5,23.0,60.0,0,150.0,150.0,150.0,34.0,45.00
3,0.0,47.75,27.17,8.6,3.89,0.42,1.45,637.0,15.48,48.43,...,0.64,2.5,23.0,60.0,0,150.0,150.0,150.0,34.0,48.00
4,637.0,47.75,27.17,8.6,3.89,0.42,1.45,0.0,15.48,48.43,...,0.64,2.5,23.0,60.0,0,150.0,150.0,150.0,34.0,50.32

In [286]:
# total binders

original_features = df.columns.to_list()
total_binders = ['GGBS_kg_m3', 'FlyAsh_kg_m3', 'SF_kg_m3']
df['Total_Binders'] = df['GGBS_kg_m3'] + df['FlyAsh_kg_m3'] + df['SF_kg_m3']
df.head()

,GGBS_kg_m3,GGBS_CaO_%,GGBS_SiO2_%,GGBS_Al2O3_%,GGBS_MgO_%,GGBS_Fe2O3_%,GGBS_SO3_%,FlyAsh_kg_m3,FA_CaO_%,FA_SiO2_%,...,SiO2 to Na2O (silicate modulus),Curing_Temperature,Relative Humidity,Condition,Length (mm),Breadth (mm),height (mm),CS 7 day (Mpa),CS 28 day (Mpa),Total_Binders
0,0.0,47.75,27.17,8.6,3.89,0.42,1.45,650.0,15.48,48.43,...,2.5,23.0,60.0,0,150.0,150.0,150.0,34.0,29.00,650.0
1,650.0,47.75,27.17,8.6,3.89,0.42,1.45,0.0,15.48,48.43,...,2.5,23.0,60.0,0,150.0,150.0,150.0,34.0,40.00,650.0
2,325.0,47.75,27.17,8.6,3.89,0.42,1.45,325.0,15.48,48.43,...,2.5,23.0,60.0,0,150.0,150.0,150.0,34.0,45.00,650.0
3,0.0,47.75,27.17,8.6,3.89,0.42,1.45,637.0,15.48,48.43,...,2.5,23.0,60.0,0,150.0,150.0,150.0,34.0,48.00,637.0
4,637.0,47.75,27.17,8.6,3.89,0.42,1.45,0.0,15.48,48.43,...,2.5,23.0,60.0,0,150.0,150.0,150.0,34.0,50.32,637.0

In [287]:
# total SiO2

original_features = df.columns.to_list()
total_sio2 = ['GGBS_SiO2_%', 'FA_SiO2_%', 'SF_SiO2_%']
df['Total_SiO2'] = ((df['GGBS_kg_m3'] * df['GGBS_SiO2_%']) + (df['FlyAsh_kg_m3'] * df['FA_SiO2_%']) + (df['SF_kg_m3'] * df['SF_SiO2_%'])) / df['Total_Binders']
df.head()

,GGBS_kg_m3,GGBS_CaO_%,GGBS_SiO2_%,GGBS_Al2O3_%,GGBS_MgO_%,GGBS_Fe2O3_%,GGBS_SO3_%,FlyAsh_kg_m3,FA_CaO_%,FA_SiO2_%,...,Curing_Temperature,Relative Humidity,Condition,Length (mm),Breadth (mm),height (mm),CS 7 day (Mpa),CS 28 day (Mpa),Total_Binders,Total_SiO2
0,0.0,47.75,27.17,8.6,3.89,0.42,1.45,650.0,15.48,48.43,...,23.0,60.0,0,150.0,150.0,150.0,34.0,29.00,650.0,48.43
1,650.0,47.75,27.17,8.6,3.89,0.42,1.45,0.0,15.48,48.43,...,23.0,60.0,0,150.0,150.0,150.0,34.0,40.00,650.0,27.17
2,325.0,47.75,27.17,8.6,3.89,0.42,1.45,325.0,15.48,48.43,...,23.0,60.0,0,150.0,150.0,150.0,34.0,45.00,650.0,37.80
3,0.0,47.75,27.17,8.6,3.89,0.42,1.45,637.0,15.48,48.43,...,23.0,60.0,0,150.0,150.0,150.0,34.0,48.00,637.0,48.43
4,637.0,47.75,27.17,8.6,3.89,0.42,1.45,0.0,15.48,48.43,...,23.0,60.0,0,150.0,150.0,150.0,34.0,50.32,637.0,27.17

In [288]:
# total CaO

original_features = df.columns.to_list()
total_cao = ['GGBS_CaO_%', 'FA_CaO_%', 'SF_CaO_%']
df['Total_CaO'] = ((df['GGBS_kg_m3'] * df['GGBS_CaO_%']) + (df['FlyAsh_kg_m3'] * df['FA_CaO_%']) + (df['SF_kg_m3'] * df['SF_CaO_%'])) / df['Total_Binders']
df.head()

,GGBS_kg_m3,GGBS_CaO_%,GGBS_SiO2_%,GGBS_Al2O3_%,GGBS_MgO_%,GGBS_Fe2O3_%,GGBS_SO3_%,FlyAsh_kg_m3,FA_CaO_%,FA_SiO2_%,...,Relative Humidity,Condition,Length (mm),Breadth (mm),height (mm),CS 7 day (Mpa),CS 28 day (Mpa),Total_Binders,Total_SiO2,Total_CaO
0,0.0,47.75,27.17,8.6,3.89,0.42,1.45,650.0,15.48,48.43,...,60.0,0,150.0,150.0,150.0,34.0,29.00,650.0,48.43,15.480
1,650.0,47.75,27.17,8.6,3.89,0.42,1.45,0.0,15.48,48.43,...,60.0,0,150.0,150.0,150.0,34.0,40.00,650.0,27.17,47.750
2,325.0,47.75,27.17,8.6,3.89,0.42,1.45,325.0,15.48,48.43,...,60.0,0,150.0,150.0,150.0,34.0,45.00,650.0,37.80,31.615
3,0.0,47.75,27.17,8.6,3.89,0.42,1.45,637.0,15.48,48.43,...,60.0,0,150.0,150.0,150.0,34.0,48.00,637.0,48.43,15.480
4,637.0,47.75,27.17,8.6,3.89,0.42,1.45,0.0,15.48,48.43,...,60.0,0,150.0,150.0,150.0,34.0,50.32,637.0,27.17,47.750

In [289]:
# total Al2O3

original_features = df.columns.to_list()
total_Al2O3 = ['GGBS_Al2O3_%', 'FA_Al2O3_%', 'SF_Al2O3_%']
df['Total_Al2O3'] = ((df['GGBS_kg_m3'] * df['GGBS_Al2O3_%']) + (df['FlyAsh_kg_m3'] * df['FA_Al2O3_%']) + (df['SF_kg_m3'] * df['SF_Al2O3_%'])) / df['Total_Binders']
df.head()

,GGBS_kg_m3,GGBS_CaO_%,GGBS_SiO2_%,GGBS_Al2O3_%,GGBS_MgO_%,GGBS_Fe2O3_%,GGBS_SO3_%,FlyAsh_kg_m3,FA_CaO_%,FA_SiO2_%,...,Condition,Length (mm),Breadth (mm),height (mm),CS 7 day (Mpa),CS 28 day (Mpa),Total_Binders,Total_SiO2,Total_CaO,Total_Al2O3
0,0.0,47.75,27.17,8.6,3.89,0.42,1.45,650.0,15.48,48.43,...,0,150.0,150.0,150.0,34.0,29.00,650.0,48.43,15.480,17.150
1,650.0,47.75,27.17,8.6,3.89,0.42,1.45,0.0,15.48,48.43,...,0,150.0,150.0,150.0,34.0,40.00,650.0,27.17,47.750,8.600
2,325.0,47.75,27.17,8.6,3.89,0.42,1.45,325.0,15.48,48.43,...,0,150.0,150.0,150.0,34.0,45.00,650.0,37.80,31.615,12.875
3,0.0,47.75,27.17,8.6,3.89,0.42,1.45,637.0,15.48,48.43,...,0,150.0,150.0,150.0,34.0,48.00,637.0,48.43,15.480,17.150
4,637.0,47.75,27.17,8.6,3.89,0.42,1.45,0.0,15.48,48.43,...,0,150.0,150.0,150.0,34.0,50.32,637.0,27.17,47.750,8.600

In [290]:
# ratios
df['SiO2 / Al2O3'] = df['Total_SiO2'] / df['Total_Al2O3']
df['CaO / Al2O3'] = df['Total_CaO'] / df['Total_Al2O3']
df['CaO / SiO2'] = df['Total_CaO'] / df['Total_SiO2']

In [291]:
df.head()

,GGBS_kg_m3,GGBS_CaO_%,GGBS_SiO2_%,GGBS_Al2O3_%,GGBS_MgO_%,GGBS_Fe2O3_%,GGBS_SO3_%,FlyAsh_kg_m3,FA_CaO_%,FA_SiO2_%,...,height (mm),CS 7 day (Mpa),CS 28 day (Mpa),Total_Binders,Total_SiO2,Total_CaO,Total_Al2O3,SiO2 / Al2O3,CaO / Al2O3,CaO / SiO2
0,0.0,47.75,27.17,8.6,3.89,0.42,1.45,650.0,15.48,48.43,...,150.0,34.0,29.00,650.0,48.43,15.480,17.150,2.823907,0.902624,0.319637
1,650.0,47.75,27.17,8.6,3.89,0.42,1.45,0.0,15.48,48.43,...,150.0,34.0,40.00,650.0,27.17,47.750,8.600,3.159302,5.552326,1.757453
2,325.0,47.75,27.17,8.6,3.89,0.42,1.45,325.0,15.48,48.43,...,150.0,34.0,45.00,650.0,37.80,31.615,12.875,2.935922,2.455534,0.836376
3,0.0,47.75,27.17,8.6,3.89,0.42,1.45,637.0,15.48,48.43,...,150.0,34.0,48.00,637.0,48.43,15.480,17.150,2.823907,0.902624,0.319637
4,637.0,47.75,27.17,8.6,3.89,0.42,1.45,0.0,15.48,48.43,...,150.0,34.0,50.32,637.0,27.17,47.750,8.600,3.159302,5.552326,1.757453

In [292]:
# # drop columns
# cols_drop = ['Total_SiO2', 'Total_CaO', 'Total_Al2O3', 'GGBS_MgO_%', 'GGBS_Fe2O3_%', 'GGBS_SO3_%', 'FA_MgO_%', 'FA_Fe2O3_%', 'FA_SO3_%', 'SF_MgO_%', 'SF_Fe2O3_%', 'SF_SO3_%']
# columns_to_drop = total_binders + total_sio2 + total_cao + total_Al2O3 + cols_drop
# print(columns_to_drop)
# df.drop(columns=columns_to_drop, inplace=True)
# df.head()

In [293]:
# calculate volume
df['Dim_Volume'] = df['Length (mm)'] * df['Breadth (mm)'] * df['height (mm)']
df.drop(columns=['Length (mm)', 'Breadth (mm)', 'height (mm)'], inplace=True)
df.head()

,GGBS_kg_m3,GGBS_CaO_%,GGBS_SiO2_%,GGBS_Al2O3_%,GGBS_MgO_%,GGBS_Fe2O3_%,GGBS_SO3_%,FlyAsh_kg_m3,FA_CaO_%,FA_SiO2_%,...,CS 7 day (Mpa),CS 28 day (Mpa),Total_Binders,Total_SiO2,Total_CaO,Total_Al2O3,SiO2 / Al2O3,CaO / Al2O3,CaO / SiO2,Dim_Volume
0,0.0,47.75,27.17,8.6,3.89,0.42,1.45,650.0,15.48,48.43,...,34.0,29.00,650.0,48.43,15.480,17.150,2.823907,0.902624,0.319637,3375000.0
1,650.0,47.75,27.17,8.6,3.89,0.42,1.45,0.0,15.48,48.43,...,34.0,40.00,650.0,27.17,47.750,8.600,3.159302,5.552326,1.757453,3375000.0
2,325.0,47.75,27.17,8.6,3.89,0.42,1.45,325.0,15.48,48.43,...,34.0,45.00,650.0,37.80,31.615,12.875,2.935922,2.455534,0.836376,3375000.0
3,0.0,47.75,27.17,8.6,3.89,0.42,1.45,637.0,15.48,48.43,...,34.0,48.00,637.0,48.43,15.480,17.150,2.823907,0.902624,0.319637,3375000.0
4,637.0,47.75,27.17,8.6,3.89,0.42,1.45,0.0,15.48,48.43,...,34.0,50.32,637.0,27.17,47.750,8.600,3.159302,5.552326,1.757453,3375000.0

In [294]:
plt.figure(figsize=(15,12))
sns.heatmap(df.corr(), annot=True, cmap='coolwarm')
plt.savefig('new_corr.png', dpi=300)
plt.close()

In [295]:
(df.isnull().mean())*100

GGBS_kg_m3                          0.000000
GGBS_CaO_%                          0.000000
GGBS_SiO2_%                         0.000000
GGBS_Al2O3_%                        0.000000
GGBS_MgO_%                          0.000000
GGBS_Fe2O3_%                        0.000000
GGBS_SO3_%                          0.000000
FlyAsh_kg_m3                        0.000000
FA_CaO_%                            0.000000
FA_SiO2_%                           0.000000
FA_Al2O3_%                          0.000000
FA_MgO_%                            0.000000
FA_Fe2O3_%                          0.000000
FA_SO3_%                            0.000000
SF_kg_m3                            0.000000
SF_CaO_%                            0.000000
SF_SiO2_%                           0.000000
SF_Al2O3_%                          0.000000
SF_MgO_%                            0.000000
SF_Fe2O3_%                          0.000000
SF_SO3_%                            0.000000
Total NaOH (kg in 1m3 mix)          0.000000
Concentration (M) NaOH              0.000000
Total Na2SiO3 (kg in 1m3 of mix)    0.000000
Coarse Aggregate (kg/m3)            0.000000
Fine Aggregates (kg/m3)             0.000000
Water (kg/m3)                       0.000000
Activator_Binder_Ratio              0.000000
Water_Binder_Ratio                  0.000000
Superplasticizer_%                  0.000000
SiO2 to Na2O (silicate modulus)     0.000000
Curing_Temperature                  0.000000
Relative Humidity                   0.000000
Condition                           0.000000
CS 7 day (Mpa)                      0.000000
CS 28 day (Mpa)                     0.000000
Total_Binders                       0.000000
Total_SiO2                          0.224719
Total_CaO                           0.224719
Total_Al2O3                         0.224719
SiO2 / Al2O3                        0.224719
CaO / Al2O3                         0.224719
CaO / SiO2                          0.224719
Dim_Volume                          0.000000
dtype: float64

In [296]:
dataset.dtypes

GGBS_kg_m3                          float64
GGBS_CaO_%                          float64
GGBS_SiO2_%                         float64
GGBS_Al2O3_%                        float64
GGBS_MgO_%                          float64
GGBS_Fe2O3_%                        float64
GGBS_SO3_%                          float64
FlyAsh_kg_m3                        float64
FA_CaO_%                            float64
FA_SiO2_%                           float64
FA_Al2O3_%                          float64
FA_MgO_%                            float64
FA_Fe2O3_%                          float64
FA_SO3_%                            float64
SF_kg_m3                            float64
SF_CaO_%                            float64
SF_SiO2_%                           float64
SF_Al2O3_%                          float64
SF_MgO_%                            float64
SF_Fe2O3_%                          float64
SF_SO3_%                            float64
Total NaOH (kg in 1m3 mix)          float64
Concentration (M) NaOH              float64
Total Na2SiO3 (kg in 1m3 of mix)    float64
Coarse Aggregate (kg/m3)            float64
Fine Aggregates (kg/m3)             float64
Water (kg/m3)                       float64
Activator_Binder_Ratio              float64
Water_Binder_Ratio                  float64
Superplasticizer_%                  float64
SiO2 to Na2O (silicate modulus)     float64
Curing_Temperature                  float64
Relative Humidity                   float64
Condition                             int64
Length (mm)                         float64
Breadth (mm)                        float64
height (mm)                         float64
CS 7 day (Mpa)                      float64
CS 28 day (Mpa)                     float64
dtype: object

In [297]:
df['Total_SiO2'] = df['Total_SiO2'].fillna(df['Total_SiO2'].mean())
df['Total_CaO'] = df['Total_CaO'].fillna(df['Total_CaO'].mean())
df['Total_Al2O3'] = df['Total_Al2O3'].fillna(df['Total_Al2O3'].mean())

df['SiO2 / Al2O3'] = df['SiO2 / Al2O3'].fillna(df['SiO2 / Al2O3'].mean())
df['CaO / Al2O3'] = df['SiO2 / Al2O3'].fillna(df['CaO / Al2O3'].mean())
df['CaO / SiO2'] = df['CaO / SiO2'].fillna(df['CaO / SiO2'].mean())

(df.isnull().mean())*100

GGBS_kg_m3                          0.0
GGBS_CaO_%                          0.0
GGBS_SiO2_%                         0.0
GGBS_Al2O3_%                        0.0
GGBS_MgO_%                          0.0
GGBS_Fe2O3_%                        0.0
GGBS_SO3_%                          0.0
FlyAsh_kg_m3                        0.0
FA_CaO_%                            0.0
FA_SiO2_%                           0.0
FA_Al2O3_%                          0.0
FA_MgO_%                            0.0
FA_Fe2O3_%                          0.0
FA_SO3_%                            0.0
SF_kg_m3                            0.0
SF_CaO_%                            0.0
SF_SiO2_%                           0.0
SF_Al2O3_%                          0.0
SF_MgO_%                            0.0
SF_Fe2O3_%                          0.0
SF_SO3_%                            0.0
Total NaOH (kg in 1m3 mix)          0.0
Concentration (M) NaOH              0.0
Total Na2SiO3 (kg in 1m3 of mix)    0.0
Coarse Aggregate (kg/m3)            0.0
Fine Aggregates (kg/m3)             0.0
Water (kg/m3)                       0.0
Activator_Binder_Ratio              0.0
Water_Binder_Ratio                  0.0
Superplasticizer_%                  0.0
SiO2 to Na2O (silicate modulus)     0.0
Curing_Temperature                  0.0
Relative Humidity                   0.0
Condition                           0.0
CS 7 day (Mpa)                      0.0
CS 28 day (Mpa)                     0.0
Total_Binders                       0.0
Total_SiO2                          0.0
Total_CaO                           0.0
Total_Al2O3                         0.0
SiO2 / Al2O3                        0.0
CaO / Al2O3                         0.0
CaO / SiO2                          0.0
Dim_Volume                          0.0
dtype: float64

In [298]:
df.head()

,GGBS_kg_m3,GGBS_CaO_%,GGBS_SiO2_%,GGBS_Al2O3_%,GGBS_MgO_%,GGBS_Fe2O3_%,GGBS_SO3_%,FlyAsh_kg_m3,FA_CaO_%,FA_SiO2_%,...,CS 7 day (Mpa),CS 28 day (Mpa),Total_Binders,Total_SiO2,Total_CaO,Total_Al2O3,SiO2 / Al2O3,CaO / Al2O3,CaO / SiO2,Dim_Volume
0,0.0,47.75,27.17,8.6,3.89,0.42,1.45,650.0,15.48,48.43,...,34.0,29.00,650.0,48.43,15.480,17.150,2.823907,2.823907,0.319637,3375000.0
1,650.0,47.75,27.17,8.6,3.89,0.42,1.45,0.0,15.48,48.43,...,34.0,40.00,650.0,27.17,47.750,8.600,3.159302,3.159302,1.757453,3375000.0
2,325.0,47.75,27.17,8.6,3.89,0.42,1.45,325.0,15.48,48.43,...,34.0,45.00,650.0,37.80,31.615,12.875,2.935922,2.935922,0.836376,3375000.0
3,0.0,47.75,27.17,8.6,3.89,0.42,1.45,637.0,15.48,48.43,...,34.0,48.00,637.0,48.43,15.480,17.150,2.823907,2.823907,0.319637,3375000.0
4,637.0,47.75,27.17,8.6,3.89,0.42,1.45,0.0,15.48,48.43,...,34.0,50.32,637.0,27.17,47.750,8.600,3.159302,3.159302,1.757453,3375000.0

In [299]:
print(df.shape)
df.to_csv('../data/final_engineered_ds.csv', index=False)

(445, 44)